### ISSUE TITLE
Dragon in the wrong location

### ISSUE THREAD

**Issue by rcl2748** [confuser/BarAPI#53] opened 2015-04-14 03:32 UTC
Hi Confuserr, I am the developer of BossMessage (the most popular bossbar messaging plugin on bukkitdev), and I was trying to make it use your BarAPI plugin. BarAPI seems to work fine, except that the FakeDragon appears to be in the wrong location, instead of deep underneath the player, it appears on the same Y and Z level as the player, while the X is decreased. This bug occurs on the latest 1.8 server build. Please fix so everyone who were using BarAPI can continue using it. Thank you.

**Comment by confuser** [comment] 2015-04-14 14:38
I've updated the Known Caveats format on v3.3 on BukktiDev to make it even more obvious as to the cause.

http://dev.bukkit.org/bukkit-plugins/bar-api/files/7-bar-api-v3-3/

FYI it's a client side bug which won't be fixed until 1.9

**Closed by confuser** 2015-04-14 14:38 UTC

**Comment by gogobebe2** [comment] 2015-04-15 20:46
Thanks confuser. :)

**Comment by rcl2748** [comment] 2015-04-16 00:16
@gogobebe2 We don't know anything. It is not even technically a "bug", and probably was done on purpose. Let's hope it will all be fixed asap.
